import numpy as np

def trans_to_Spherical_coordinates(pos_data: np.ndarray) -> np.ndarray: ...
def trans_to_Cartesian_coordinates(sphere_coor: np.ndarray) -> np.ndarray: ...
def fibonacci_sampling(Num_sampling: int = ...) -> tuple[np.ndarray, np.ndarray]: ...
def vector_length3d(pos: np.ndarray) -> np.ndarray: ...
def unit_vector3d(pos: np.ndarray) -> np.ndarray: ...
def Matmul(v1: np.ndarray, v2: np.ndarray) -> np.ndarray: ...
def iso_profile_by_moi(points: np.ndarray, pas: np.ndarray, res_b: float, res_c: float) -> np.ndarray: ...
def iso_profile_by_pair(points: np.ndarray, pas: np.ndarray, res_b: float, res_c: float) -> np.ndarray: ...
