repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit  # if use local, repo: local
    rev: v0.11.0
    hooks:
      - id: ruff
        name: ruff check
        files: '^src/gal3d/'
        args: ["check"]
      - id: ruff-format
        name: ruff format
        files: '^src/gal3d/'

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        files: '^src/gal3d/'
        args: ["--config-file=pyproject.toml"]
        pass_filenames: true