import numpy as np

def Shift(pos: np.ndarray, cen: np.ndarray) -> np.ndarray: ...
def Rotate(pos: np.ndarray, mat: np.ndarray) -> np.ndarray: ...
def Matmul(v1: np.ndarray, v2: np.ndarray) -> np.ndarray: ...
def Hadamard(v1: np.ndarray, v2: np.ndarray) -> np.ndarray: ...
def Dot(v0: np.ndarray, v1: np.ndarray) -> float: ...
def vector_length3d(pos: np.ndarray) -> np.ndarray: ...
def unit_vector3d(pos: np.ndarray) -> np.ndarray: ...
def trans_to_Spherical_coordinates(pos_data: np.ndarray) -> np.ndarray: ...
def trans_to_Cartesian_coordinates(sphere_coor: np.ndarray) -> np.ndarray: ...
def RobustLength2d(v0: float, v1: float) -> float: ...
def RotateAndShift(pos: np.ndarray, matrix: np.ndarray, pc: np.ndarray) -> np.ndarray: ...