#!/usr/bin/env python3
"""Clean Cython build artifacts and rebuild extensions in place."""
import argparse
import os
import re
import shutil
from pathlib import Path

from _log_utils import logger

def is_cython_generated(filepath: Path) -> bool:
    """Return True if *filepath* was generated by Cython (via well-known header markers).

    At least two of the following markers must be present to reduce false positives:
    ``Generated by Cython``, ``BEGIN: Cython Metadata``, ``END: Cython Metadata``,
    and the combination of ``#include "Python.h"`` with distutils/module_name hints.
    """
    try:
        with open(filepath, encoding="utf-8", errors="ignore") as fh:
            content = "".join(fh.readline() for _ in range(20))
        markers = [
            "Generated by Cython" in content,
            "BEGIN: Cython Metadata" in content,
            "END: Cython Metadata" in content,
            re.search(r'#include "Python\.h"', content) is not None
            and ("module_name" in content or "distutils" in content),
        ]
        return sum(markers) >= 2
    except (UnicodeDecodeError, IOError):
        return False

def get_modified_pyx_files(project_root: Path) -> set[Path]:
    """Return .pyx files that are newer than their generated .c/.cpp counterparts."""
    logger.step("Checking for modified .pyx files…")
    pyx_files: set[Path] = set()

    src_dir = project_root / "src"
    for pyx_file in src_dir.glob("**/*.pyx"):
        # Look for corresponding .c or .cpp file
        c_file = pyx_file.with_suffix(".c")
        cpp_file = pyx_file.with_suffix(".cpp")

        if c_file.exists():
            if os.path.getmtime(pyx_file) > os.path.getmtime(c_file):
                pyx_files.add(pyx_file)
                logger.item(f"Modified: {pyx_file.relative_to(project_root)}")
        elif cpp_file.exists():
            if os.path.getmtime(pyx_file) > os.path.getmtime(cpp_file):
                pyx_files.add(pyx_file)
                logger.item(f"Modified: {pyx_file.relative_to(project_root)}")
        else:
            pyx_files.add(pyx_file)
            logger.item(f"New file: {pyx_file.relative_to(project_root)}")

    return pyx_files

def get_corresponding_generated_files(
    project_root: Path, modified_pyx_files: set[Path]
) -> set[Path]:
    """Return Cython-generated .c/.cpp files for the given modified .pyx files."""
    generated: set[Path] = set()
    src_dir = project_root / "src"

    for ext in (".c", ".cpp"):
        for f in src_dir.glob(f"**/*{ext}"):
            if is_cython_generated(f) and f.with_suffix(".pyx") in modified_pyx_files:
                generated.add(f)

    return generated

def clean_build_artifacts(*, all_mode: bool = False) -> None:
    """Remove Cython build artifacts and cached Python files."""
    project_root = Path(__file__).parent.parent.absolute()

    logger.header(
        f"gal3d build-artifact cleaner  —  {'FULL' if all_mode else 'SELECTIVE'} mode"
    )
    logger.step(f"Project root: {project_root}")

    # ── build/ directory ──────────────────────────────────────────────────────
    build_dir = project_root / "build"
    if all_mode and build_dir.exists():
        logger.item("Removing build/")
        shutil.rmtree(build_dir)

    src_dir = project_root / "src"
    modified_pyx_files: set[Path] = set() if all_mode else get_modified_pyx_files(project_root)

    # ── .so / .pyd extension files ────────────────────────────────────────────
    ext_count = 0
    if all_mode:
        logger.step("Removing compiled extension files…")
        for ext in (".so", ".pyd"):
            for f in src_dir.glob(f"**/*{ext}"):
                logger.item(f"Removing: {f.relative_to(project_root)}")
                f.unlink()
                ext_count += 1
    else:
        logger.step("Identifying extension files for modified sources…")
        # Collect into a set first to avoid double-deletion when patterns overlap
        to_remove: set[Path] = set()
        for pyx_file in modified_pyx_files:
            relative_path = pyx_file.relative_to(src_dir)
            stem_glob = relative_path.parent / relative_path.stem
            for ext in (".so", ".pyd"):
                # Precise match using the actual directory structure
                for f in src_dir.glob(f"{stem_glob}*{ext}"):
                    to_remove.add(f)
                # Broader fallback: any subdirectory, same stem
                for f in src_dir.glob(f"**/{relative_path.stem}*{ext}"):
                    to_remove.add(f)
        for f in sorted(to_remove):
            logger.item(f"Removing: {f.relative_to(project_root)}")
            f.unlink()
            ext_count += 1

    if ext_count:
        logger.success(f"Removed {ext_count} extension file(s)")
    else:
        logger.done("No extension files needed removal")

    # ── Cython-generated C/C++ files ──────────────────────────────────────────
    cython_removed = 0
    cython_kept = 0

    if all_mode:
        logger.step("Removing Cython-generated C/C++ files…")
        for ext in (".c", ".cpp"):
            for f in src_dir.glob(f"**/*{ext}"):
                if is_cython_generated(f):
                    logger.item(f"Removing: {f.relative_to(project_root)}")
                    f.unlink()
                    cython_removed += 1
                else:
                    cython_kept += 1
    else:
        logger.step("Identifying generated C/C++ files for modified sources…")
        for f in get_corresponding_generated_files(project_root, modified_pyx_files):
            logger.item(f"Removing: {f.relative_to(project_root)}")
            f.unlink()
            cython_removed += 1
        for ext in (".c", ".cpp"):
            for f in src_dir.glob(f"**/*{ext}"):
                if is_cython_generated(f):
                    cython_kept += 1

    if cython_removed:
        logger.success(f"Removed {cython_removed} Cython-generated C/C++ file(s)")
    if cython_kept:
        logger.done(f"Kept {cython_kept} non-generated C/C++ file(s)")

    # ── __pycache__ and .pyc (full mode only) ─────────────────────────────────
    pycache_count = 0
    pyc_count = 0

    if all_mode:
        logger.step("Removing __pycache__ directories…")
        for d in src_dir.glob("**/__pycache__"):
            logger.item(f"Removing: {d.relative_to(project_root)}")
            shutil.rmtree(d)
            pycache_count += 1
        if pycache_count:
            logger.success(f"Removed {pycache_count} __pycache__ director(ies)")

        logger.step("Removing .pyc files…")
        for f in src_dir.glob("**/*.pyc"):
            logger.item(f"Removing: {f.relative_to(project_root)}")
            f.unlink()
            pyc_count += 1
        if pyc_count:
            logger.success(f"Removed {pyc_count} .pyc file(s)")

    # ── summary ───────────────────────────────────────────────────────────────
    total = ext_count + cython_removed + pycache_count + pyc_count
    if total:
        logger.summary(f"Cleanup complete — {total} item(s) removed")
    else:
        logger.warning("Nothing to clean. Use --all for a full cleanup.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Clean Cython build artifacts.",
        epilog="By default, only cleans artifacts related to modified Cython files.",
    )
    parser.add_argument("--all", action="store_true", help="Clean all build artifacts")
    args = parser.parse_args()
    clean_build_artifacts(all_mode=args.all)


if __name__ == "__main__":
    main()