#!/usr/bin/env python3
"""
Clean Cython build artifacts and rebuild extensions in place.
"""
import argparse
import os
import re
import shutil
from pathlib import Path
from datetime import datetime

# ANSI color codes for terminal output
class Colors:
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def log(msg, color=None, bold=False, timestamp=False):
    """Print a formatted log message."""
    prefix = f"[{datetime.now().strftime('%H:%M:%S')}] " if timestamp else ""
    
    if color:
        msg = f"{color}{msg}{Colors.ENDC}"
    
    if bold:
        msg = f"{Colors.BOLD}{msg}{Colors.ENDC}"
    
    print(f"{prefix}{msg}")

def is_cython_generated(filepath):
    """
    Check if a file is generated by Cython by looking for Cython generation markers.
    
    Multiple markers are checked to avoid false positives:
    1. "Generated by Cython" in first line
    2. "BEGIN: Cython Metadata" section
    3. Typical Cython-generated include patterns
    """
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            # Read first few lines to check for Cython markers
            content = ''.join(f.readline() for _ in range(20))
            
            # Check for multiple markers
            markers = [
                "Generated by Cython" in content,
                "BEGIN: Cython Metadata" in content,
                "END: Cython Metadata" in content,
                re.search(r'#include "Python\.h"', content) is not None and 
                    ("module_name" in content or "distutils" in content)
            ]
            
            # If at least two markers match, consider it a Cython file
            return sum(markers) >= 2
            
    except (UnicodeDecodeError, IOError):
        return False

def get_modified_pyx_files(project_root):
    """
    Get list of .pyx files that have been modified since their corresponding .c/.cpp files were generated.
    
    Returns:
        set: Set of .pyx file paths that have been modified
    """
    log("Checking for modified .pyx files...", Colors.CYAN)
    pyx_files = set()
    
    # Find all .pyx files
    src_dir = project_root / "src"
    for pyx_file in src_dir.glob("**/*.pyx"):
        # Look for corresponding .c or .cpp file
        c_file = pyx_file.with_suffix('.c')
        cpp_file = pyx_file.with_suffix('.cpp')
        
        # Check if .pyx is newer than .c/.cpp or if .c/.cpp doesn't exist
        if c_file.exists():
            if os.path.getmtime(pyx_file) > os.path.getmtime(c_file):
                pyx_files.add(pyx_file)
                log(f"  - Modified: {pyx_file.relative_to(project_root)}", Colors.BLUE)
        elif cpp_file.exists():
            if os.path.getmtime(pyx_file) > os.path.getmtime(cpp_file):
                pyx_files.add(pyx_file)
                log(f"  - Modified: {pyx_file.relative_to(project_root)}", Colors.BLUE)
        else:
            # No corresponding generated file, include it anyway
            pyx_files.add(pyx_file)
            log(f"  - New file: {pyx_file.relative_to(project_root)}", Colors.BLUE)
    
    return pyx_files

def get_corresponding_generated_files(project_root, modified_pyx_files):
    """
    Get list of .c/.cpp files corresponding to the modified .pyx files.
    
    Args:
        project_root: Project root directory
        modified_pyx_files: Set of modified .pyx file paths
    
    Returns:
        set: Set of .c/.cpp file paths to be removed
    """
    generated_files = set()
    src_dir = project_root / "src"
    
    # Find all Cython-generated files
    for ext in [".c", ".cpp"]:
        for file in src_dir.glob(f"**/*{ext}"):
            # Only include if it's Cython-generated and corresponds to a modified .pyx
            if is_cython_generated(file):
                pyx_file = file.with_suffix('.pyx')
                if pyx_file in modified_pyx_files:
                    generated_files.add(file)
    
    return generated_files

def clean_build_artifacts(all_mode=False):
    """Remove Cython build artifacts and cached Python files."""
    project_root = Path(__file__).parent.parent.absolute()
    
    log(f"Scanning project root: {project_root}", Colors.CYAN, timestamp=True)

    if all_mode:
        log("Running in FULL CLEANUP mode", Colors.WARNING, bold=True)
    else:
        log("Running in SELECTIVE CLEANUP mode (only modified files)", Colors.CYAN, bold=True)
    
    # delete build directory
    build_dir = project_root / "build"
    if all_mode and build_dir.exists():
        log(f"Removing build directory: {build_dir}", Colors.BLUE)
        shutil.rmtree(build_dir)

    src_dir = project_root / "src"
        
    # Get modified .pyx files
    modified_pyx_files = get_modified_pyx_files(project_root) if not all_mode else set()
    
    # delete .so .pyd
    ext_count = 0
    if all_mode:
        log(f"Scanning source directory: {src_dir}", Colors.CYAN)

        for ext in [".so", ".pyd"]:
            for file in src_dir.glob(f"**/*{ext}"):
                log(f"  - Removing: {file.relative_to(project_root)}", Colors.BLUE)
                file.unlink()
                ext_count += 1
        log(f"✓ Removed {ext_count} extension files", Colors.GREEN, bold=True)
        
    else:
        # In selective mode, only remove extensions for modified files
        log("Identifying extension files for modified sources...", Colors.CYAN)        
        for pyx_file in modified_pyx_files:
            # Determine module name from .pyx file path
            relative_path = pyx_file.relative_to(src_dir)
            module_path = str(relative_path.parent / relative_path.stem).replace('/', '.')
            
            # Look for corresponding .so/.pyd files
            for ext in [".so", ".pyd"]:
                # Pattern to match various Python extension naming conventions
                patterns = [
                    f"**/*{module_path}*{ext}",  # General pattern
                    f"**/{relative_path.stem}*{ext}"  # Fallback pattern
                ]
                
                for pattern in patterns:
                    for file in src_dir.glob(pattern):
                        log(f"  - Removing: {file.relative_to(project_root)}", Colors.BLUE)
                        file.unlink()
                        ext_count += 1
        
        if ext_count > 0:
            log(f"✓ Removed {ext_count} extension files", Colors.GREEN, bold=True)
        else:
            log("✓ No extension files needed removal", Colors.GREEN)

    # delete Cython generated C/C++ files
    cython_files_removed = 0
    cython_files_kept = 0
    
    if all_mode:
        for ext in [".c", ".cpp"]:
            for file in src_dir.glob(f"**/*{ext}"):
                if is_cython_generated(file):
                    log(f"  - Removing: {file.relative_to(project_root)}", Colors.BLUE)
                    file.unlink()
                    cython_files_removed += 1
                else:
                    cython_files_kept += 1
    else:
        # Get corresponding generated files for modified .pyx files
        log("Identifying generated files for modified sources...", Colors.CYAN)
        generated_files = get_corresponding_generated_files(project_root, modified_pyx_files)
        
        for file in generated_files:
            log(f"  - Removing: {file.relative_to(project_root)}", Colors.BLUE)
            file.unlink()
            cython_files_removed += 1
        
        # Count remaining (kept) C/C++ files
        for ext in [".c", ".cpp"]:
            for file in src_dir.glob(f"**/*{ext}"):
                if is_cython_generated(file):
                    cython_files_kept += 1

    log(f"✓ Removed {cython_files_removed} Cython-generated C/C++ files", Colors.GREEN, bold=True)
    if cython_files_kept > 0:
        log(f"✓ Kept {cython_files_kept} C/C++ files", Colors.GREEN)


    # Clean __pycache__ directories if in all_mode
    pycache_count = 0
    if all_mode:
        for pycache_dir in src_dir.glob("**/__pycache__"):
            log(f"  - Removing: {pycache_dir.relative_to(project_root)}", Colors.BLUE)
            shutil.rmtree(pycache_dir)
            pycache_count += 1

        log(f"✓ Removed {pycache_count} __pycache__ directories", Colors.GREEN, bold=True)

    # Clean .pyc files if in all_mode
    pyc_count = 0
    if all_mode:
        log("Scanning for .pyc files...", Colors.CYAN)
        for pyc_file in src_dir.glob("**/*.pyc"):
            log(f"  - Removing: {pyc_file.relative_to(project_root)}", Colors.BLUE)
            pyc_file.unlink()
            pyc_count += 1

        log(f"✓ Removed {pyc_count} .pyc files", Colors.GREEN, bold=True)

    # Summary
    total_removed = ext_count + cython_files_removed + pycache_count + pyc_count
    log(f"CLEANUP SUMMARY: {total_removed} items removed", Colors.GREEN, bold=True)
    
    if not all_mode and total_removed == 0:
        log("No files needed cleaning. Use --all to perform a full cleanup.", Colors.WARNING)

def main():
    """Main function to clean"""
    parser = argparse.ArgumentParser(
        description="Clean Cython build artifacts.",
        epilog="By default, only cleans artifacts related to modified Cython files."
    )
    parser.add_argument("--all", action="store_true", help="Clean all build artifacts")
    args = parser.parse_args()
    clean_build_artifacts(all_mode=args.all)


if __name__ == "__main__":
    main()