import numpy as np

def centroid(pos: np.ndarray) -> np.ndarray: ...
def center_of_mass(pos: np.ndarray, mass: np.ndarray) -> np.ndarray: ...
def shrink_sphere_center(
    pos: np.ndarray,
    weight: np.ndarray,
    min_points: int,
    particles_for_second_radius: int,
    shrink_factor: float,
    starting_rmax: float,
    itermax: int
) -> tuple[np.ndarray, float, float, int]: ...
def moment_of_inertia(pos: np.ndarray, m: np.ndarray) -> np.ndarray: ...
def solve_eigenvalues(I: np.ndarray, sort_descending: bool = True) -> tuple[np.ndarray, np.ndarray]: ...
def abc_vect(pos: np.ndarray, mass: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
