




# General settings
[general]

# Update stub for plugins
update_stub = False

# Batch size for processing, prevent memory overflow
min_batchsize = 200000

# Number of threads to use for parallel processing, -1 use (available cores)/2
number_of_threads = -1

# Use Cython for acceleration; if False and numba is available, use numba
use_cython = True

# Use double precision for rendering
render_double = False


# Logging settings
[logger]

# 10: debug, 20: info, 30: warning, 40: error, 50: critical error.
level = 20

# Enable saving logs to a file
save_file = False

# File name for the log file
file_name = gal3d.log

# Log file level
file_level = 20

# Stream level
stream_level = 20