





[general]

update_stub = False

batchsize = 200000  # prevent memory overflow





[logger]

# 10: debug, 20: info, 30: warning, 40: error, 50: critical error.
level = 20

save_file = False

file_name = gal3d.log

file_level = 20

stream_level = 20