





[Point]

r_max = 30 # all particles within 30 kpc

mode = Density

estimator = DensityEstimatorKNN

k_nearest = 32

# for TNG50 soften length = 0.288, 10 * 0.288
r_cut = 2.88



[Field]

n_ray = 1024

ray_method = fibonacci

inner = 0.144       #  soften length/2

inner_mode = dist


# ~ mean mass / (volume for 3 soften length):  6e4 / (4pi/3 * (2*0.288)**3)
outer = 2e4

outer_mode = value

n_step = 500

step_mode = log

interpolator = LU

isodensity_method = pair 

from_rays_func = False

res_b = 0.2

res_c = 0.1

iso_step = 500

isodensity_interpolator = LU



[Shape]

coordinate = EulerShift

geometry = Ellipsoid_S


error_func = sums_dev_rscale

error_method = isodensity_dcall



[Optimizer]

optimizer = OptimizerScipy

algorithm = Powell



[fit]
r_min = 0.864       # 3* soften radius

r_max = 28.8        # 100* soften radius

n_step = 300

step_mode = log

[Visualize]

ModelProjector = ProjectorLineIntegration

[Characterize]

Characterizer = Bar


