import numpy as np

from .show import ImageData

class PyCubicSplineSmoothingKernel:
    def __call__(self, r: float) -> float: ...
    def density(self, r: float) -> float: ...
    def columnDensity(self, R: float) -> float: ...

class PyCubicSplineSmoothingKernelFloat:
    def __call__(self, r: float) -> float: ...
    def density(self, r: float) -> float: ...
    def columnDensity(self, R: float) -> float: ...

class PyRenderImage:
    def add_particle(self, x: np.ndarray, y: np.ndarray, mass: np.ndarray, hsml: np.ndarray) -> None: ...
    def circle_vs_canvas(self, x: float, y: float, hsml: float) -> int: ...
    def get_image(self) -> ImageData: ...

class PyRenderImageFloat:
    def add_particle(self, x: np.ndarray, y: np.ndarray, mass: np.ndarray, hsml: np.ndarray) -> None: ...
    def circle_vs_canvas(self, x: float, y: float, hsml: float) -> int: ...
    def get_image(self) -> ImageData: ...

def get_kernel() -> PyCubicSplineSmoothingKernel | PyCubicSplineSmoothingKernelFloat: ...
def get_render_image(
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    nx: int,
    ny: int,
    kernel: PyCubicSplineSmoothingKernel | PyCubicSplineSmoothingKernelFloat,
    subsample_nx: int,
    subsample_ny: int,
    numthreads: int = ...,
) -> PyRenderImage | PyRenderImageFloat: ...
