import numpy as np

def vector_length3d(pos: np.ndarray) -> np.ndarray: ...
def unit_vector3d(pos: np.ndarray) -> np.ndarray: ...
def f_ellipsoid(a: float, b: float, c: float, pos: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def f_ellipsoid_jacobian(a: float, b: float, c: float, pos: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def IntersectRaysEllipsoid(a: float, b: float, c: float, pos: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def f_ray_ellipsoid(a: float, b: float, c: float, pos: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def IntersectLinesEllipsoid(a: float, b: float, c: float, pos1: np.ndarray, pos2: np.ndarray) -> np.ndarray: ...
